START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260622032935_AddTaskActivityHistory') THEN
    CREATE TABLE task_activities (
        "Sequence" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Id" uuid NOT NULL,
        "TaskId" character varying(128) NOT NULL,
        "WorkflowRunId" uuid,
        "CorrelationId" uuid NOT NULL,
        "Category" character varying(64) NOT NULL,
        "Type" character varying(128) NOT NULL,
        "Summary" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_task_activities" PRIMARY KEY ("Sequence"),
        CONSTRAINT "FK_task_activities_workflow_runs_WorkflowRunId" FOREIGN KEY ("WorkflowRunId") REFERENCES workflow_runs ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260622032935_AddTaskActivityHistory') THEN
    CREATE UNIQUE INDEX "IX_task_activities_Id" ON task_activities ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260622032935_AddTaskActivityHistory') THEN
    CREATE INDEX "IX_task_activities_TaskId_Sequence" ON task_activities ("TaskId", "Sequence");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260622032935_AddTaskActivityHistory') THEN
    CREATE INDEX "IX_task_activities_WorkflowRunId" ON task_activities ("WorkflowRunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260622032935_AddTaskActivityHistory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260622032935_AddTaskActivityHistory', '10.0.9');
    END IF;
END $EF$;
COMMIT;

